name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake g++ make

    - name: Install PCL
      run: |
        sudo apt-get install -y libpcl-dev

    - name: Install Vulkan
      run: |
        sudo apt-get install -y libvulkan-dev

    - name: Install VTK
      run: |
        sudo apt-get install -y libvtk9-dev

    - name: Set up OpenCV
      run: |
        sudo apt install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
        git clone https://github.com/opencv/opencv.git
        cd opencv
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: Install Boost
      run: |
        sudo apt-get install -y libboost-all-dev

    - name: Install Eigen3
      run: |
        sudo apt-get install -y libeigen3-dev

    - name: Build
      run: |
        cd building_reconstruction
        mkdir build
        cd build
        cmake ..
        cmake --build .
