name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake g++ make

    - name: Install Boost
      run: |
        sudo apt update
        sudo apt install build-essential
        wget https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
        tar -xzvf boost_1_75_0.tar.gz
        cd boost_1_75_0
        ./bootstrap.sh --prefix=/usr/local
        sudo ./b2 install
        ls /usr/local/include/boost

    - name: Install PCL
      run: |
        sudo apt-get install -y libpcl-dev

    - name: Install Vulkan
      run: |
        sudo apt-get install -y libvulkan-dev

    - name: Install VTK
      run: |
        sudo apt-get install -y libvtk9-dev

    - name: Set up OpenCV
      run: |
        sudo apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
        sudo apt-get install -y libopencv-dev
      
    - name: Install Eigen3
      run: |
        sudo apt-get install -y libeigen3-dev

    - name: Build
      run: |
        cd building_reconstruction
        mkdir build
        cd build
        cmake ..
        cmake --build . -- VERBOSE=1

