name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake g++ make

    - name: Build
      run: |
        cd building_reconstruction
        mkdir build
        cd build
        cmake ..
        cmake --build .
